# Generated by Django 6.0.5 on 2026-05-23 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='datasets/%Y/%m/%d/')),
                ('file_type', models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'Excel')], max_length=10)),
                ('rows', models.IntegerField(default=0)),
                ('columns', models.JSONField(default=list)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_cleaned', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
